
[commands]

  [commands.commands]

    [commands.commands.reboot]
      command = "/opt/mydevices/command-ctrl.sh reboot"
      max_execution_duration = "1s"

    [commands.commands.remote-ctrl]
      command = "/opt/mydevices/command-ctrl.sh remote-ctrl"
      max_execution_duration = "15s"

    [commands.commands.update]
      command = "/opt/mydevices/command-ctrl.sh update"
      max_execution_duration = "20m"

    [commands.commands.cmd]
      command = "/opt/mydevices/command-ctrl.sh remote-cmd"
      max_execution_duration = "5m"

[integration]
  marshaler = "protobuf"

  [integration.mqtt]
    max_token_wait = "60s"

    [integration.mqtt.auth]
      type = "azure_iot_hub"

        [integration.mqtt.auth.azure_iot_hub.provisioning]
          endpoint = "global.azure-devices-provisioning.net"
          scope = "0ne0006B4D6"

[meta_data]

  [meta_data.dynamic]
    execution_interval = "10m0s"
    max_execution_duration = "1m0s"

    [meta_data.dynamic.commands]
      apn = "/opt/mydevices/metadata.sh apn"
      battery_critical = "/opt/mydevices/metadata.sh battery_critical"
      cert_expiration = "/opt/mydevices/metadata.sh cert_expiration"
      charge_complete = "/opt/mydevices/metadata.sh charge_complete"
      charge_fault = "/opt/mydevices/metadata.sh charge_fault"
      charging = "/opt/mydevices/metadata.sh charging"
      chirpstack_version = "/opt/mydevices/metadata.sh chirpstack_version"
      dps_client_version = "/opt/mydevices/metadata.sh dps_client_version"
      eth_ip = "/opt/mydevices/metadata.sh eth_ip"
      eui = "/opt/mydevices/metadata.sh eui"
      firmware_version = "/opt/mydevices/metadata.sh firmware_version"
      imei = "/opt/mydevices/metadata.sh imei"
      imsi = "/opt/mydevices/metadata.sh imsi"
      mac = "/opt/mydevices/metadata.sh mac"
      manufacturer = "/opt/mydevices/metadata.sh manufacturer"
      marshaler = "/opt/mydevices/metadata.sh marshaler"
      model = "/opt/mydevices/metadata.sh model"
      power_source = "/opt/mydevices/metadata.sh power_source"
      rssi = "/opt/mydevices/metadata.sh rssi"
      serial = "/opt/mydevices/metadata.sh serial"
      voltage = "/opt/mydevices/metadata.sh voltage"
      wwan_ip = "/opt/mydevices/metadata.sh wwan_ip"
