
[commands]

  [commands.commands]

    [commands.commands.reboot]
      command = "/mnt/data/myd/myd/command-ctrl.sh reboot"
      max_execution_duration = "1s"

    [commands.commands.remote-ctrl]
      command = "/mnt/data/myd/myd/command-ctrl.sh remote-ctrl"
      max_execution_duration = "15s"

    [commands.commands.update]
      command = "/mnt/data/myd/myd/command-ctrl.sh update"
      max_execution_duration = "20m"
    
    [commands.commands.cmd]
      command = "/mnt/data/myd/myd/command-ctrl.sh remote-cmd"
      max_execution_duration = "5m"

[integration]
  marshaler = "protobuf"

  [integration.mqtt]
    max_token_wait = "60s"

    [integration.mqtt.auth]
      type = "azure_iot_hub"

        [integration.mqtt.auth.azure_iot_hub.provisioning]
          endpoint = "global.azure-devices-provisioning.net"
          scope = "0ne0006B4D6"
          
[meta_data]

  [meta_data.dynamic]
    execution_interval = "10m0s"
    max_execution_duration = "1m0s"

    [meta_data.dynamic.commands]
      cert_expiration = "/mnt/data/myd/myd/metadata.sh cert_expiration"
      chirpstack_version = "/mnt/data/myd/myd/metadata.sh chirpstack_version"
      dps_client_version = "/mnt/data/myd/myd/metadata.sh dps_client_version"
      eth_ip = "/mnt/data/myd/myd/metadata.sh eth_ip"
      eui = "/mnt/data/myd/myd/metadata.sh eui"
      firmware_version = "/mnt/data/myd/myd/metadata.sh firmware_version"
      hardware_version = "/mnt/data/myd/myd/metadata.sh hardware_version"
      mac = "/mnt/data/myd/myd/metadata.sh mac"
      manufacturer = "/mnt/data/myd/myd/metadata.sh manufacturer"
      marshaler = "/mnt/data/myd/myd/metadata.sh marshaler"
      model = "/mnt/data/myd/myd/metadata.sh model"
      serial = "/mnt/data/myd/myd/metadata.sh serial"
